---
language: python
services: docker

env:
  - distro: ubuntu1604
  - distro: ubuntu1404

script:
  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  - 'docker exec --tty ${container_id} env TERM=xterm service awslogs status'
  - 'docker exec --tty ${container_id} env TERM=xterm cat /var/log/awslogs.log'

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      - secure:  "FBo51kh6FYQIdfTrx6PZaHCkdLczltP3igNBFbIRdJ5TsyO9uNLWXlIzu69bHmZ2RnraAt5ts8ArvCgrfcVLF/7nfp6m6WUOeukQz1/9VgPuSKt+KyEyL6hLGR9wQnrGfk0jmlP7Zj/PsPxOd+PnK4OZnjpZ1unnL3VpkITUP5pNIyWJFG1bBAgOECXXHaQAjejWack2bvNhfEw6XF55ey9PRPmyx0icRnAaMipMIVKBPZApUPqo0oLVsgdFZcZukAyEhQgmCilSqRaQkiu7x7GY2KAi5VOHPFnnikcMWkt3palN1FNdnyt6Ie4cY6FdjBmrlNLlQgeto7XX6Io1kkLuNLqsnfw49HkXBIKQRZ1me8UYTKV/1A8SXt7ixQWfbr2E0VzN9XR5/c0cDDDyLKubB16BLQKkUOCtdfgCvc/Pkh5rtxe5Tu2m+jsiAzeOiJMS61dA4B4kCpOPACkmzSOpNenbQgpBhe7Frjys+MCmF+LiR6/toRgVZndYK+uuxikvSsW3y4FdaflZUkLGiFGRW6dn+RKbLK1n1tszJprxQHADMUGiaEGV3pTsDfHgYPJoJ/VxBusdZk8ivcx6lHdWxlQ0GDWnLR8yRH/3Hin3mlVQlxLhFrsnHUKbLxLtOeCOrT9HPPdqxRhaZE2sla/8XqQuYArzlCtQtuifzHc="
