language: python
services: docker
env:
- distro: ubuntu1604
- distro: ubuntu1404
script:
- export container_id=$(date +%s)
- export cleanup=false
- wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
- chmod +x ${PWD}/tests/test.sh
- "${PWD}/tests/test.sh"
- docker exec --tty ${container_id} env TERM=xterm curl localhost:9200
notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    rooms:
      secure: jrE3JvcBQqRRPxmAY516i4onWgzmGP/Radbba+e2Wif50eyue08lsqKPJnSn05RfYfUi+RhfHtuwfRl1wVi0514yRcCd03+VtsywnFcjNp1JIZYtOAgQaxjwVkjqHfM7sin7ThfWiU/xlsTqKBnN5UuNJZQV3BhixI0j4mjatV0MfitE9x47Q/OK8TSyIcKh/92eDdm/8VzLBrTgy8hncJEgX58dX3KWMVku0J3KFoGWOb5nj0ozzRCFUT3xtJ9eKL58MVazqt/1CRq9EFy0afNytRV1WUnWrndwOrQznzVX5gy1wEMRcJFJ+fZxAXZqAKEFGRr0MQxwGiBRg8nsh1+WD2qC6r4Vr2Xm+QiaOc5KnblWLPhznOrmh1+VzPfYorSoz+DkcoKTkxmJ1iyumaVECe3aXzdb/Z3lmbO4ryIIpASdGGh9av8rdfA5deT7uWmTMLrYgiV1j2Olw/Xt+NP64NmwTbKe5xTINepQLJHYjzyA70H16gV4rHKaXBrlzYXXzdRjFsGkrn4T8SGWpAr72CRRIh4o+6V/18Z9g6kI9WGn0Slg1WuwjfbJ1SJHdSW3uwXwbzP84Ia0NkhmGqvZVRWQhoP89k1xo67nkeVmKV7mX8HbxhMnPwyhs49nW4g++WqibMQuEoH2hRA85vrfcwjqgvR1D8CEHDpbFTk=
