---
- name: Ensure APT depedencies are present
  apt:
    name:
      - cron
      - python
      - libyaml-dev
    state: present
    update_cache: true
    cache_valid_time: 120

- name: Ensure source path is created
  file:
    path: "/var/awslogs"
    state: directory
    mode: 0755

- name: Ensure awslogs.conf is updated
  template:
    src: awslogs.conf.j2
    dest: /var/awslogs/awslogs.conf
  notify: restart awslogs

- name: Check it awslogs is already installed
  stat:
    path: /var/awslogs/bin/awslogs-agent-launcher.sh
  register: awslogs_stat

- name: Download install script
  get_url:
    url: https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py
    dest: /tmp/awslogs.py
    mode: 0755
  when: not awslogs_stat.stat.exists

- name: Ensue the CloudWatch logs agent is installed
  command: >
    python /tmp/awslogs.py -n -r {{ aws_region }}
    -c /var/awslogs/awslogs.conf
  when: not awslogs_stat.stat.exists

- name: Ensure awslogs is started and enabled at startup
  service:
    name: awslogs
    state: started
    enabled: true

- name: Get current configuration files
  command: ls -1 /var/awslogs/etc/config
  register: conf_files
  changed_when: false

- name: Define files to preserve
  set_fact:
    conf_files_to_preserve: "{{ cw_logs_files | map(attribute='name') | list }}"
  changed_when: false

- name: Remove stale log configuration files
  file:
    path: "/var/awslogs/etc/config/{{ item }}"
    state: absent
  with_items: "{{ conf_files.stdout_lines }}"
  when: item not in conf_files_to_preserve
  notify: restart awslogs

- name: Ensure log configurations are updated
  template:
    src: log-config.conf.j2
    dest: "/var/awslogs/etc/config/{{ item.name }}"
  with_items: "{{ cw_logs_files }}"
  notify: restart awslogs
