---
- name: Ensure the APT cache is updated
  apt:
    update_cache: yes
    cache_valid_time: 120

- name: "Ensure {{ source_path }} is created"
  file:
    path: "{{ source_path }}"
    state: directory
    mode: 755

- name: Download install script
  get_url:
    url: https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py
    dest: /tmp/awslogs-agent-setup.py
    mode: 550

- name: Create awslogs.conf
  template:
    src: awslogs.conf.j2
    dest: "{{ logging_config_file }}"
  register: awslogs

- name: Install the CloudWatch logs agent
  shell: "python /tmp/awslogs-agent-setup.py -n -r {{ aws_region }} -c {{ logging_config_file }}"
  when: awslogs|changed
  notify: restart awslogs

- name: Ensure awslogs is started and enabled at startup
  service:
    name: awslogs
    state: started
    enabled: yes
