---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-cloudwatch-logs
      cw_logs_files:
        - name: syslog
          args:
            log_group_name: syslog
            log_stream_name: ubuntu
            datetime_format: '%b %d %H:%M:%S'
            time_zone: UTC
            file: /var/log/syslog
            file_fingerprint_lines: 1-5
            multi_line_start_pattern: '^\s+.*'
            initial_position: start_of_file
            encoding: utf_8
            buffer_duration: 5000
            batch_count: 10000
            batch_size: 1048576
        - name: auth
          args:
            log_group_name: auth.log
            log_stream_name: ubuntu
            datetime_format: '%b %d %H:%M:%S'
            time_zone: UTC
            file: /var/log/auth.log
            file_fingerprint_lines: 1-5
            multi_line_start_pattern: '^\s+.*'
            initial_position: start_of_file
            encoding: utf_8
            buffer_duration: 5000
            batch_count: 10000
            batch_size: 1048576
